* Motivation
    ** Frustrations from the mainstream PL
&&& Push up the constraint


&&& complexity gets trimmed the more tight the function domain is. 

Functions returning filtered results, Maybes or validation errors have the complexity of that optionality handling inside the function
and then of handling the result that needs to encode the required invariants.

We all understand the benefits of constraining the domain of a function at the type level and constraining the number of possible implementations 
through parametricity.

Pushing this further we need to demand that other invariants not expressible at the "type level" are also enforced through decidability.

very important for business invariants
* Intersection / conjunction

** The way to encode adhoc properties on elements
   e.g. newtype in haskell

   newtype propA 
   newttpe propB

** you would probably create a new newtype AandB
   You cannot combine the with a fundamental connective like And or intersection.

================================

* Uncle Bob: where is your composability now?    

===============================

* We are missing composability at the type level

==============================
